### ISSUE TITLE
Data Lake library needs to use Shade plugin to prevent class path versioning issues

### ISSUE THREAD

**Issue by nicolehaugen79** [Azure/azure-data-lake-store-java#9]
We have noticed an issue with some of the Azure Mgmt SDKs in that they don't repackage their dependencies into a custom Microsoft namespace, using either the Maven Shade plugin or the Gradle Shadow plugin. Without using these plugins, this can cause versioning issues when this SDK is used in conjunction with other open source libraries using similar, but different versions of dependencies (e.g. 'class path hell'). Often, when class path hell occurs, you'll see an exception at run time saying "NoSuchMethod" because there are two versions of the same dependency used, but the wrong version gets loaded for one of the libraries that uses it. Using the Shade\Shadow plugins will prevent this.

I'm logging this issue because in looking at the POM for the azure-data-lake-store-java library, it doesn't reference the Maven Shade plugin. Please take a look at using this plugin to ensure that version conflicts don't occur when using the azure-data-lake-store-jave SDK.

Here's a link to a similar issue that was logged against the Document DB library that describes this type of problem in greater detail since a versioning conflict issue was found when using the Document DB library in combination with the App Insights SDK. Azure/azure-documentdb-java#90

**Comment by asikaria-msft** [comment]
@nicolehaugen79, currently this is by design, so trying to understand the driving use case here. Which of our transitive dependencies do you see a conflict with? 

Currently to address the version dependency issue, we intentionally keep our dependencies to a minimum - slf4j and jackson-core only. The versions we use are fairly well tested across different versions of upstream libraries and ISVs have successfully integrated the SDK into various big-data systems, so just curious to understand which one of the dependencies is causing conflicts for you.
